### ISSUE TITLE
output of string have weird characters

### ISSUE THREAD

**Issue by nonvwvnon** [mafonya/c_hide_strings#1]
attach is the screenshot.

![screenshot_2018-08-21_16-22-59](https://user-images.githubusercontent.com/81169/44389865-83477b00-a51b-11e8-9b26-9bd111384908.png)

**Comment by nonvwvnon** [comment]
add a {0} to char str.  char str[512]={0};
there is still a weird char at end of the char.
This could be the reason it return 8 as the length for word 'Example' ?

![screenshot_2018-08-21_19-13-19](https://user-images.githubusercontent.com/81169/44398473-76368600-a533-11e8-94a1-0753937c6fb9.png)

**Comment by yeomann** [comment]
same problem i am experiencing :d

**Comment by yeomann** [comment]
ok i did sovled it. i will create pull request for that.

**Comment by ed588** [comment]
easiest way to fix this is to add `buf[0] = '\0'` at the start of the `c` function
